name: Frontend Build

on:
  pull_request:
    branches: [ master]
    paths:
    - 'frontend/**'
  

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x]

    steps:
    - name: Decrypt frontend.env
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'Do next build'
      working-directory: ./frontend
      run: |
        npm ci
        npm run action-build
        echo "build is passing"